create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', target_titles jsonb not null default '[]', skills jsonb not null default '[]', locations jsonb not null default '[]', preferences jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.resumes (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, file_name text not null, file_type text not null, file_size bigint not null, file_hash text not null, storage_path text, extracted_text text, status text not null default 'pending', created_at timestamptz not null default now(), unique(user_id,file_hash));
create table if not exists public.resume_parse_runs (id uuid primary key default gen_random_uuid(), resume_id uuid not null references public.resumes(id) on delete cascade, parser_type text not null, provider text, model text, prompt_version text, result jsonb not null default '{}', warnings jsonb not null default '[]', requires_review boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.career_evidence (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, resume_id uuid references public.resumes(id) on delete set null, category text not null, normalized_value text not null, original_text text not null, confidence numeric not null check(confidence between 0 and 1), verification_status text not null default 'unverified', created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.resumes enable row level security; alter table public.resume_parse_runs enable row level security; alter table public.career_evidence enable row level security;
create policy "profile owner" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "resume owner" on public.resumes for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "parse owner" on public.resume_parse_runs for all using (exists(select 1 from public.resumes r where r.id=resume_id and r.user_id=auth.uid())) with check (exists(select 1 from public.resumes r where r.id=resume_id and r.user_id=auth.uid()));
create policy "evidence owner" on public.career_evidence for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

